### ISSUE TITLE
Ensure reproducibility when using MT Geant4 with Celeritas offloading

### ISSUE THREAD

**Issue by amandalund** [celeritas-project/celeritas#1023]
In MT Geant4 applications, the scheduling of events is done dynamically. This means events are not guaranteed to be mapped to the same threads over multiple runs. For reproducibility, Geant4 reseeds each worker thread's RNG for each event. We will need to do something similar with our RNG states in Celeritas to make sure simulations with Celeritas offloading are reproducible.

The Geant4 `/run/eventModulo <N> <seedOnce>` UI command can be used to control the chunk size and seed frequency:
- The chunk size `N` defaults to `int(sqrt(num_events / num_threads))` when `N` is 0.
- `seedOnce` controls how often the RNG on each worker thread is seeded. If the default value (0) is used, each thread's RNG will be seeded for each event and the simulation will be reproducible. If `seedOnce` is set to 1, the RNG will only be seeded for the first event on each worker thread.

**Comment by sethrj** [comment]
See #1049, #1052
