### ISSUE TITLE
Add G4VG support for ALICE Geant4 geometry components

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#1068]
From @sawenzel:

> For the moment, I seem to be blocked by 2 error messages:
> 
> a) unsupported solid type G4DisplacedSolid
> 
>  b) unsupported type 'G4PVDivision' for physical volume 'ZNTX_PV' (corresponding LV: "ZNTX"@0xaaaabefaf6d0 (ID=106))
> 
> - G4DisplacedSolids are sometimes used inside booleans. Not sure why you don't see this with CMS but
> it could be a speciality of the GDML constructed with ROOT.  We would need to implement the solid in VecGeom first and ensure it works on CUDA.
> 
> - The other issue about G4PVDivision can probably be solved in the geometry converter by simply creating distinct VecGeom physical volumes or maybe there is an option in the ROOT geometry exporter not to use divisions in the output... I'll take a look.

From discussions with the VecGeom team it sounds like we might be able to reduce the displaced solids to regular solids by propagating the displacement into the "placement" of the physical volumes.

For the physical volumes, we should be able to replicate them manually.

**Comment by sawenzel** [comment]
> From discussions with the VecGeom team it sounds like we might be able to reduce the displaced solids to regular solids by propagating the displacement into the "placement" of the physical volumes.

Yes, that's a good idea. In Geant4 a boolean has 2 logical volumes as members whereas in VecGeom there are 2 placed volumes. A logical displaced volume should be straightforwardly convertible.

**Comment by sawenzel** [comment]
@sethrj : After inspection of the conversion code, I believe you should already be doing the right thing. But there might be a wrong assumption that only the second volume could be a displaced volume. In fact, after switching on assertations, I see:

```
.../app/celer-g4/celer-g4.cc:297: critical: While running input_gun.json: celeritas/ext/g4vg/SolidConverter.cc:696:
celeritas: Geant4 error: celer0001 failed:
    precondition failed: !dynamic_cast<G4DisplacedSolid const*>(solids[0])
```
So simply extending the treatment to the first volume might be enough. Shall I provide a PR?

**Comment by sethrj** [comment]
@sawenzel Yes that was an assumption inherited from an earlier version of the vecgeom->Geant4 converter. I actually just found the same thing and am about to submit the PR! Thanks though. If you'd like to add the PV expansion we'd love to include your contribution 😄

**Comment by sawenzel** [comment]
Since you have the code already I would say just go ahead -:)

I believe the assumption might be based on some documentation but potentially the gdml converter or some other unit does not seem to respect it.

**Comment by sawenzel** [comment]
I made a PR with the replica treatment. Feel free to use it or take it as inspiration. I am now locally able to convert my test geometry.
