### ISSUE TITLE
Integrate Perfetto for optional CPU profiling

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#1224]
It looks like [Perfetto](https://github.com/google/perfetto), the Google performance/tracing tool, could be useful to integrate into Celeritas to measure performance. It might be straightforward to wrap their [tracing SDK](https://perfetto.dev/docs/instrumentation/tracing-sdk) underneath `ScopedProfiling`.

**Comment by esseivaju** [comment]
After looking at more Perfetto features, I think integrating it would be useful, at least supporting the basic slices and counters events. 

First, we still have the `ScopedProfiling` feature of recording and displaying function calls on a timeline, which can be used if CUDA/HIP is unavailable. Perfetto also supports counters, e.g. we could have an active track counter updated each step which would be displayed on a timeline (similar to the memory usage below).

<img width="1542" alt="image" src="https://github.com/celeritas-project/celeritas/assets/7202402/2ded6b87-15e4-486d-881c-2333a52d8dde">

Then, if we want to support Linux [ftrace](https://kernel.org/doc/Documentation/trace/ftrace.txt) API (requires root privilege), we can find out anything that the kernel is doing: e.g. which processes/threads are scheduled on which CPU cores, memory usage, enter/exit a syscall.

The first picture below illustrates which threads are scheduled on CPU5, the status of these threads, and their syscalls. The second picture shows the memory usage for the celer-sim process only.

<img width="1415" alt="image" src="https://github.com/celeritas-project/celeritas/assets/7202402/f93eca2c-f6f9-45c0-89bc-10d676d8236c">

<img width="1469" alt="image" src="https://github.com/celeritas-project/celeritas/assets/7202402/e47c475b-b041-471e-9459-2d1c12fccf89">


In addition to visualization on the Web Interface, there is also a SQL interface ( accessible via either a Python API or the web interface). For example, we can compute the average time per Celeritas action:  

<img width="1231" alt="image" src="https://github.com/celeritas-project/celeritas/assets/7202402/39143247-3c29-42d4-9656-74c490337f4f">

**Comment by sethrj** [comment]
That's awesome @esseivaju ! Let's do it. I'm curious how this Google-developed tool compares to the in-house CERN performance tools.

**Comment by esseivaju** [comment]
Are you referring to AdaptivePerf?

**Comment by sethrj** [comment]
@drbenmorgan @wdconinc asked about profiling based on particle type/logical volume in Geant4, and I thought we could potentially use this same technology in Geant4 to give traceable output: wrap each track's loop with the particle type as the label; wrap each step with the volume as the label, wrap each DoIt with the process label?

**Comment by drbenmorgan** [comment]
@sethrj, Maxim Potokhin at BNL also asked about this in the context of EIC. We did have a partial scoped profiling system in Geant4, but it never really got fleshed out. There's clearly a demand for it though, so if we could port in/across the Celeritas design, that could be a good solution. Something to discuss with people at the Geant4 collaboration meeting.

**Comment by sethrj** [comment]
Sounds great! See you in a couple weeks 😄
