### ISSUE TITLE
Implement verification scheme

### ISSUE THREAD

**Issue by stognini** [celeritas-project/celeritas#145]
# Background

As new physics models and processes are now included or underway, a validation scheme is necessary. Geant4 is being constantly validated against data and previous versions, along with independent validations carried forward by experiments. As such, the initial plan is to validate Celeritas with Geant4 only (no external data or theory).

# Requirements

## Geant4 simulation app
- Interface should provide an easy selection of:
  - [x] One or more EM Standard Physics processes.
  - [x] Primary type, vertex location, direction, and starting energy.
  - [x] Geometry may be loaded either _i)_ programmatically, so that updates to material/element/geometry can be done quickly (this option is mostly for hardcoded demo apps); or _ii)_ parsing gdml files, for validating against a given geometry that is loaded into Celeritas.
  - [x] Provide option for _i)_ a smaller output (no step data) that could handle millions of tracks, and _ii)_ a full output for detailed inspection.
  
## Validation
- [ ] Provide analysis scripts to be used as a starting point for each individual validation.

A standardized checklist for simulations input parameters and validation results is still to be determined, although accumulated quantities are preferred at this point.

The final goal is a generic validation system that applies to each and every model, both individually and combined, resulting in a final set of standardized plots and tables that can be automatically generated for future Celeritas updates.

**Comment by sethrj** [comment]
@stognini Can you add a link to the right directory in the validation repo and then mark this issue as closed?

**Comment by stognini** [comment]
The validation is ready to be used and it is available in the benchmarks repo, which includes the geant4 simulation app and a few macros in utils/ for plotting the results.

https://github.com/celeritas-project/benchmarks/tree/master/geant4-validation-app
