### ISSUE TITLE
Add production cuts and energy limits

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#146]
The PhysicsParams (?) should take per-material (or maybe just use global for now?) "production cuts", which are particle- and material-dependent lower energy bounds for creating secondaries. Also update the Moller/Bhabha scattering so that its lower energy limits are based on these production cuts rather than a hard-coded lower energy.

Since there's an interplay between the process cross sections, the cutoffs, and even some models, perhaps the host data needs a separate helper class during setup. 

Actually the cutoff management is probably more appropriate as a separate helper class, since during interaction the particle properties being interrogated (at least in the M/B case) are *not* the incident particle's state.

**Comment by sethrj** [comment]
@amandalund I forgot that @stognini was working on importing and bringing cuts online. Y'all can work together on this if you'd like? Unless everyone objects to missing Granholm's pep talk at 2 eastern, let's discuss next steps at the 2pm meeting today.

**Comment by sethrj** [comment]
To summarize our discussions so far (please @whokion and @stognini and correct me if I'm wrong):
- "Cuts" are input by the user as distances (minimum range for a step) and transformed at Geant4 startup time to energy values. These values are hardcoded for 4 particle types -- gamma, electron, positron, proton.
- "Production" cuts are cutoffs applied while creating/producing secondary particles. If the secondary is below the energy range for the production cut, its value is set to zero.
- "Range" cuts are for particles in flight. Once their energy drops below a certain value (back-calculated earlier from the range) then their energy is deposited locally. For electrons, the resulting zero-energy particle is killed; for positrons, annihilation should produce gammas; and gammas don't have a range cut.

We discussed an alternative nomenclature to "production" (which is confusing given the common term "production run") and "range" (which is a misnomer because both cutoffs are specified by the user as a range and actually used as energy in flight). Did we come to a conclusion? Primary and secondary? (Or is "primary" only for the initial particles specified for an event...)

**Comment by amandalund** [comment]
My (limited) understanding was that Geant4 _only_ has production cuts, and once particles are created they are tracked down to zero range/energy (using only continuous energy loss when the particle energy is too low to produce secondaries above the production threshold).

**Comment by stognini** [comment]
I believe @amandalund is correct. We discussed both range and production cuts, but my understanding from the `Geant4 book for application developers` is that they are the same. Section `2.4.2 Range Cuts` specify that the range cuts are defined via `G4UserPhysicsList::SetCuts()` and are converted to energy for each material and particle type (the 4 hardcoded types). These values can be updated for individual regions of the geometry, which in turn update the `MaterialCutsCouples` that store material and cut information and are read by our `geant-exporter` app.

Sections `5.4.1 General considerations` and `5.4.6 Summary` state exactly what @amandalund mentioned:
- All particles are tracked up to zero range.
- Below the range cut (same as production cut), no secondaries are produced either to speed up simulation (via a region cut) or via a default range cut to avoid infrared divergence.

Regarding the nomenclature:
Currently the code simply has a `Cutoff` class, after your suggestion on Slack. Dropping the prefix (say, SecondaryCutoff) might avoid any biased interpretation as to what the cutoffs are, and I believe it provides a broader long term use of the class (such as encompassing tracking cuts in the future)

**Comment by sethrj** [comment]
OK, perfect. Thanks @stognini and @amandalund for the clarification. So a single cut, but two criteria must be satisfied to produce secondaries during an interaction:
- The incident particle must be above the cutoff energy for its particle type.
- The secondary particles it samples must be above *their* energy respective cutoffs.

**Comment by whokion** [comment]
@sethrj  The first bullet is still incorrect.  There is no tracking (energy) cut for the incident particle and the production cutoff is only applicable (meaningful) for associated secondary production of the physics model if the process is selected for the given step.   The more correct statement may be "The energy of incident particle must be above the cutoff energy of its "secondary" particle  if produced" (necessary condition for the energy conservation, but usually not explicitly checked during the stepping process).

**Comment by sethrj** [comment]
OK @whokion , that makes sense. I've updated my comment to reflect that. Since we "preallocate" secondaries, it might be worthwhile for our interactors to check for ability to produce before the interaction.

**Comment by stognini** [comment]
Now, there is an explanation as to why the initial cutoff values are in length, although models use the energy value to cut off secondaries:

> The cuts in stopping range allow one to say that the energy has been released at the correct space position, limiting the approximation within a given distance. On the contrary, cuts in energy imply accuracies of the energy depositions which depend on the material
