### ISSUE TITLE
Add muon physics

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#180]
Moved from #1 .

- [ ] Ionization
  - [ ] BetheBloch (ionization. 200 keV < E < 1 GeV)
  - [ ] MuBetheBloch (ionization. 1 GeV < E < 100 TeV) (
  - [ ] Bragg (mu+ ionization)
  - [ ] ICRU73Q0 (mu- ionization)
- [ ] Conversion
  - [ ] muPairProduction (electron pair production caused by muons)
- [ ] Scattering
  - [ ] WentzelVI + eCoulombScattering (Coulomb scattering)
- [ ] Bremsstrahlung
  - [x] MuBrem #257

**Comment by sethrj** [comment]
@drbenmorgan I recall you saying you would start trying to add some muon models. If so, could you tag yourself in the list above with the one you're working on?

**Comment by drbenmorgan** [comment]
@sethrj, taking a look through these now to see which is shortest/easiest - but if there's a high priority one you want, let me know.

**Comment by sethrj** [comment]
@amandalund I'm sure that @tmdelellis didn't see this old issue when y'all were dividing out tasks and creating #1272: should we close in favor of the newer one?

**Comment by amandalund** [comment]
I'd forgotten we had this one... sounds good to me.
