### ISSUE TITLE
Add single-element  test problems

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#187]
Currently our GDML test inputs all define materials with multiple elements. Until #182 is resolved (which we can worry about in the 3-6 month time frame) we'll not be able to model materials that are are alloys or mixtures.

For #54 let's define a test problem with 3-4 single-element materials in an "interesting" but simple model (something with just planes and cylinders) that roughly approximates a detector of interest in CMS/ATLAS.

**Comment by stognini** [comment]
# New simplified CMS geometry

This set of single-element concentric cylinders acts as a spherical cow in a vacuum version of CMS. The `gdml` file is produced by and available in [benchmarks/geant4-validation-app](https://github.com/celeritas-project/benchmarks/blob/master/geant4-validation-app/simple_cms.gdml).

# Composition

| Volume                                    | Composition       |
| ---------------------------- | ---------------- |
| World volume                          | H (G4_Galactic) |
| silicon tracker                         | Si                         |
| electromagnetic calorimeter | Pb                       |
| hadron calorimeter                 | C                         |
| superconducting solenoid     | Ti                        |
| iron / muon chambers            | Fe                       |

Each volume in the table can be seen (and is listed in the geometry scene) in the event display:

<img width="1058" alt="evd" src="https://user-images.githubusercontent.com/59935701/111691193-0fb59980-87fc-11eb-993c-c294682d98b8.png">

**Comment by sethrj** [comment]
Closed by #231 I think 😄
