### ISSUE TITLE
Add interface for common RNGs 

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#19]
The RNG in `random/` was based (on my suggestion) on what Shift does, using Nvidia-provided GPUs. To test RNG-based code on CPU as well, and if we want to build on HIP or another platform that doesn't provide curng adapters, we'll need something more portable. @whokion 

- [x] Move RNG classes in `random/` into `random/cuda` (see #2)
- [ ] Add similar interfaces to one or more appropriate vecmath RNGs -- either porting vecmath code, or (probably better as a first step) just providing an interface to the vecmath

As the physics develops we'll want to add additional distributions (besides "uniform"). @amandalund you might be the best person to add a `random/distributions/IsotropicDistribution` class ported from the `Nemesis/numerics/Uniform_Unit_Vector_Distribution` class. Would you be up for that or shall I?
- [x] Sample isotropic direction on device

**Comment by amandalund** [comment]
Sure, I'm on it.

**Comment by sethrj** [comment]
The decision was made to tweak the CUDA XORWOW RNG to be host-compatible rather than reimplement VecMath RNGs in Celeritas, since they were optimized for SIMD vector units.
