### ISSUE TITLE
Performance test one or more process Interactors

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#23]
Add a GPU (and CPU for reference?) test kernel for KNInteractor or some other suitable class. Run a million (maybe billion?) tracks through it, purging the secondary buffer when it fills.

**Comment by sethrj** [comment]
I'll leave this open for @tmdelellis to post some numbers from summit or other systems

**Comment by sethrj** [comment]
@tmdelellis There's been a lot going on (including my vacation), but did you have any performance numbers you could post here? Thanks!

**Comment by tmdelellis** [comment]
Ok, I have these - I will post here

**Comment by sethrj** [comment]
The benchmark repo compares [GPU results](https://github.com/celeritas-project/benchmarks/tree/master/klein-nishina/celeritas-results/analysis.ipynb) with [CPU results](https://github.com/celeritas-project/benchmarks/blob/master/klein-nishina/celeritas-results-cpu/analysis.ipynb) with Geant4 results. The Celeritas implementation is roughly 100x faster on a single Nvidia V100 compared to the same CPU-optimized implementation on a single 2.3GHz Intel Cascade Lake (Intel(R) Xeon(R) Gold 5218 CPU). I'm closing this issue but I hope to write up the results more completely.
