### ISSUE TITLE
Add compatibility with multi-threaded geant4

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#266]
Currently the Geant logger adapter uses `G4coutbuf` which isn't compatible with multithreaded geant4. Either update the code to be compatible, or just disable the logging redirect when geant is multithreaded.

**Comment by stognini** [comment]
Just a side note: Currently the `geant-exporter` is not multithread -- back when we started it, it seemed unnecessary for a minimal execution to export data. As far as I know, in G4 v11 we will have to update the `G4RunManager` call to `G4RunManagerFactory`, which will create the type of run manager we want. At that point, moving the whole exporter to a multithread option seems appropriate.

**Comment by sethrj** [comment]
I'm not so concerned about taking advantage of multiple threads; the problem is that my code fails to compile when Geant4 is built with multithreading enabled 😬 as @vrpascuzzi discovered.

**Comment by stognini** [comment]
So that means that Spack's version of G4 is single-thread by default, since it never failed on `emmet`...

**Comment by sethrj** [comment]
Huh, G4 defaults to threaded in spack and is definitely threaded on emmet... not sure what's going on if that's not failing. @vrpascuzzi do you happen to remember the change to fix this? Did you set GEANT4_BUILD_MULTITHREADED=OFF?

**Comment by stognini** [comment]
Ok, I've tested this in my local machine: built `celeritas` from scratch twice. First one with `GEANT4_BUILD_MULTITHREADED = OFF`. Then recompiled `Geant4` with that option `ON` and recompiled `celeritas` again. Compilation and tests pass on both cases.

**Comment by vrpascuzzi** [comment]
> @vrpascuzzi do you happen to remember the change to fix this? Did you set GEANT4_BUILD_MULTITHREADED=OFF?
Yes.

**Comment by sethrj** [comment]
WTF then, I don't understand why Vince's build failed. Could it be a change in a bleeding-edge geant4?

**Comment by vrpascuzzi** [comment]
I am using 10.6.2. Error with MT is:
```
<...>
75/80 Test #75: app/geant-exporter ....................***Failed    0.02 sec
/devel/bld/celeritas/app/geant-exporter: symbol lookup error: /devel/bld/celeritas/app/geant-exporter: undefined symbol: G4cout
<...>
```

**Comment by stognini** [comment]
Ohh, so it does compile. Seems like what you have here is a linking problem...
Are you running on macOS or Linux?

**Comment by vrpascuzzi** [comment]
Linux. Not sure why MT enabled would cause a link issue while MT disabled doesn't. But this is Geant-land.

**Comment by vrpascuzzi** [comment]
> the problem is that my code fails to compile when Geant4 is built with multithreading enabled
@sethrj, are you seeing this as well, or just quoting my issue?

**Comment by sethrj** [comment]
> > the problem is that my code fails to compile when Geant4 is built with multithreading enabled
> 
> @sethrj, are you seeing this as well, or just quoting my issue?

Sorry, what I meant to say was that "when Vince built, the code that I wrote which uses G4cout fails to compile"

**Comment by vrpascuzzi** [comment]
Does anyone else have the same problem on a local machine (e.g. laptop)?

**Comment by paulromano** [comment]
I don't see this issue on my laptop with a MT-enabled Geant4 build. Here's what I have installed from spack:
```
-- linux-ubuntu20.04-skylake / gcc@9.3.0 ------------------------
geant4@10.7.1~ipo~motif~opengl~python~qt+threads~vecgeom~x11 build_type=RelWithDebInfo cxxstd=14
```

**Comment by sethrj** [comment]
I have the same build on my mac, with threads, no issue :(

**Comment by stognini** [comment]
I could not reproduce the error so far, so I wonder if there is some interdependency that we are missing. @vrpascuzzi 's options are
```
make -DGEANT4_INSTALL_DATA=ON -DGEANT4_BUILD_MULTITHREADED=OFF -DGEANT4_USE_GDML=ON -DCMAKE_INSTALL_PREFIX=/opt/geant4/${G4VERSION} $SRCDIR
```
so that seems simple enough. Maybe a full inspection of all paths and options shown from the `ccmake .` in his g4 build dir could help out, if running an `ldd geant-exporter` or similar doesn't  help.

**Comment by vrpascuzzi** [comment]
I don't use spack -- call me old school, call me a fool.

As this issue is localized to only my environment, and single-threaded works fine, I'm not going to spend much time debugging it.

Thanks for all the help.

**Comment by sethrj** [comment]
@vrpascuzzi the fact that the missing symbol showed up as a runtime rather than link error suggests that it's a surprising linker flag or something... but we got past the error by changing to single threaded so let's just close as unreproducible.
