### ISSUE TITLE
Baseline performance evaluation for demo loop

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#278]
Codes:
- [x] Celeritas
  - [x] CPU #263
  - [x] GPU
  - [x] GPU (and CPU too why not) with independent geometry implementation
- [x] Geant4
- [x] AdePT

Test problems:
- [x] Stefano's simplified single-element CMS model: results at .
- [x] TestEm3 (galactic, lead, liquid argon), single element, 1D slab layers
- [x] TestEm5 (galactic, silicon), boxes

Output:
- cumulative energy distribution per detector layer, averaged for one event
- steps per particle

**Comment by sethrj** [comment]
Didn't have time to do any thorough performance comparisons in Q1. A couple of comparisons is a must for the proposal; then we can compare against adept, with rngs, other test problems, etc. later, maybe targeting a conference paper?

**Comment by sethrj** [comment]
@stognini I think we can pretty easily run TestEm3/5 in Celeritas at this point. At some point in the next few weeks could you set up the GDML inputs for those (save to `celeritas-benchmark/testem/input` maybe?) and run AdePT and Geant4 on wildstyle to get the comparative results? (For AdePT we mostly care about performance, not necessarily the diagnostics, since we're not verifying against it.)

**Comment by stognini** [comment]
Yes. At least TestEm3 was already in my todo list -- a small hiccup is that AdePT simplified the original geometries defined in the standard examples shipped with Geant4, so I'll have to be careful while reverting their VecGeom implementation back to Geant4 (which seems to be the only way for us to write gdmls, as VecGeom can load, but not write them).

**Comment by sethrj** [comment]
Done! on summit.
