### ISSUE TITLE
Add physics process management

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#28]
# Background

Geant4 implements three methods to apply a process: at-rest (decay/annihilation), along-step (continuous), and post-step (discrete) "GPIL (Get Physical Interaction Length)" and "DoIt".
- Discrete: calculates mean-free-path distance and samples an interaction from an exponential distribution. Only one discrete process is selected per step per track.
- Continuous: deposits energy and/or emits secondaries at every step. Multiple processes may happen to a single track in a step.
- Rest: always happens after a particle's kinetic energy drops to (near) zero.

It seems like a number of "continuous" processes (e.g. cerenkov, synchrotron) are implemented as discrete processes. 
(x-ray/optical photon physics are not competing with the (Geant4) standard EM physics processes for a given step,
but rather treated as additional processes top on the standard EM physics.  For example, cerenkov/scintillation processes
can be added to the ionization process if the high energy charged particle passes through a scintillation material.)

# Requirements

The process interface should:
- Set a model (to be implemented) for calculating cross sections or energy deposition rates as a function of energy.
- Sample the physical interaction length for the next step and update the interaction length left for a given track
- Map a model to `Interactor` device classes
- Apply model cutoffs before the interactor is called.
- Apply cutoffs to produced secondaries.

**Comment by whokion** [comment]
Proposals:
1) Geant4-like process management for each EM physics process registered in a physics list:
    - Compton, Photo-Electric Effect, Conversion, (photon-nuclear) for gamma
    - Ionization, Bremsstrahlung, Coulomb/Multiple scattering, (electron-nuclear) for electron
    - Ionization, Bremsstrahlung, Coulomb/Multiple scattering, Annihilation for positron
2) A generic process for each particle type (electron/positron, gamma) with a predefined set of physics
    - Gamma process
    - Electron/Positron process

The second approach will select a physics process for governing a given step, evaluate the proposed step length and call associated DoIt (Interactor) with the selected model within the single generic process for a given particle type.

**Comment by sethrj** [comment]
Per today's discussion:
- Shift has moved from launching smaller kernels with thread-to-track mapping, to launching the kernels and just masking based on the process (or in Shift nomenclature: event type)
- We'll ideally want to pre-filter to skip processes that are not applicable to any active track (e.g. for the first step if we're starting out with all of a particular particle type). Before worrying about this though we should evaluate the performance of a "null-op" process/model kernel where none of the events apply.
- Because track energy can change from continuous processes before the "winning" discrete process is selected, it's not possible to pre-select a winning *model* rather than a winning process. Thus we have to have some kind of process grouping and select a model on-the-fly.

**Comment by sethrj** [comment]
The major pieces of this are in place. The glue code will be prototyped in #54 .
