### ISSUE TITLE
Add RNG on CPU/GPU that can be compared to AdePT/Geant4

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#286]
In order to have the "most fair" comparison with AdePT (and to give the option to trade additional compute time for better PRNG statistical tests) we should implement or add a Container-compatible adapter class for a RANLUX++-based RNG. Initially we can test this out in the main code base with a compile-time switch, but I think eventually we can move to templating parts of Celeritas on a traits class that will let us swap out various implementations of geometry, RNG, etc.

**Comment by sethrj** [comment]
See https://github.com/apt-sim/AdePT/issues/41

**Comment by whokion** [comment]
If the purpose of this implementation is to compare relative performance of celeritas with respect to AdaPT (on both CPU and GPU, and their ratio), an alternative option may be testing AdePT with the default RNG of celeritas (probably Philox, which should be decided later).  I am a bit surprised that AdePT has adapted the Ranluxpp as their default pseudo-random number generator (pRNG) for their prototype even though I may guess motivation behind the choice.  I generally agree that Ranluxpp is one of efficient pRNGs, but there are many other good choices of pRNGs for both quality and performance, which can be discussed further as necessary.

**Comment by whokion** [comment]
For a reference, I put the original article on Ranluxpp, [https://arxiv.org/pdf/1705.03123.pdf]

**Comment by sethrj** [comment]
Thanks @whokion ! You're right that we don't need this performance comparison immediately and that it might be easier to add a different RNG to adept/geant for comparison purposes.

**Comment by sethrj** [comment]
I'm going to move to Q3 since this dovetails with performance portability (allowing non-CUDA).

**Comment by sethrj** [comment]
- From 2020, [Review of High‐Quality Random Number Generators](https://link.springer.com/article/10.1007/s41781-019-0034-3)
- [xoshiro](https://vigna.di.unimi.it/xorshift/)
- And there's the possibility of just including [Xorwow from rocRAND](https://github.com/ROCmSoftwarePlatform/rocRAND/blob/develop/library/include/rocrand/rocrand_xorwow.h) since it's MIT licensed and pretty self contained

**Comment by sethrj** [comment]
Infrastructure for multiple RNGs and basic xorwow was implemented in #404  . It should be trivial to implement mixmax or whatever if people think it's important for comparison purposes.
