### ISSUE TITLE
Add generic hit/step structure for Geant4 integration

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#29]
Sensitive detectors are tally regions: when a particle is inside a user-selected region of space that represents the "sensitive" component of a detector apparatus, we need to collect information about "hits" (particle travel inside a  detector) for later postprocessing (digitization, generating a simulated digital signal from the detector array from an Event based on the timing and energy deposition of track "hits").

### Associated data

Parameters (shared, read-only for a problem):
- Hash table (or for initial implementation, linear search) of `VolumeId` for sensitive regions, constructed by querying geometry's name-to-id method for user-given strings
- (?) Cutoffs for relevant particles, energy ranges?
- (?) Tolerance for spatial resolution on output

Shared
- Buffer of "hits" (detector tally events) waiting to be flushed

Each hit is a step of travel in the detector:
- Position
- Direction
- Volume ID
- Event ID
- Track ID
- Particle type
- Distance traveled over the step
- Initial and final energy on the step
- Local energy deposition (since energy loss could include emission of secondaries ?)
- Start time
Derivative quantities:
- End time over the step

Questions:
- Can these segments be combined if they're not less than the distance cut?
- The [draft requirements document](https://github.com/celeritas-project/celeritas-docs/blob/master/notes/draft-requirements-v2.pdf) says we also need information about starting/ending process for the track and step. Is that necessary for digitization or just for "mc truth"-like diagnostics? 

### Hit output

Questions:
- What's the output bandwidth requirement at GPU saturation?
- Related, what are the memory requirements of the detector output buffer? Will we need to have two buffers (one active, one being transferred to CPU asynchronously for output)?
- To run on DOE leadership systems we will need to execute a single process in parallel, requiring some sort of parallel I/O method. Can ROOT support parallel I/O? Can we do "poor man's" I/O, creating a separate output file on each process?
- Should we consider basing I/O off [ADIOS2](https://adios2.readthedocs.io/en/latest/), a data transfer and I/O framework that might enable high-performance exascale hit processing/digitization?

**Comment by sethrj** [comment]
Restrict the scope of this to focus on the immediate need of the experiment frameworks we might need to integrate with.

**Comment by sethrj** [comment]
@whokion Maybe a good initial target for this goal would be all the hit data that Geant4 can supply? We could start by supporting filtering tracks based on the detector volume (i.e. only store hits for the sensitive detectors). Can you list all the data that would be needed to reconstruct a Geant4 "hit" object?

**Comment by whokion** [comment]
@sethrj As you many know that Geant4 does not define any hit structure, but only provides G4VHit.hh (pure virtual). So, a concrete hit class and an associated sensitive detector should be created by the user based on G4Step (link to almost all low level tracking information) and G4TouchableHistory (geometry information) - therefore based on necessary Views for the celertias case.  For an example, please see their combination at https://github.com/celeritas-project/acceleritas/blob/master/app/g4hpc/include/CalorimeterHit.hh and https://github.com/celeritas-project/acceleritas/blob/master/app/g4hpc/src/CalorimeterSD.cc#L34 (i.e, a concrete implementation of G4VSensitiveDetector::ProcessHits as an example).   Then, the final output data is a collection of G4THitsCollection classes for all SensitiveDetectors and probably additional Event, Run and auxiliary information which can be stored in an event head bank (if data unit is an event).  Normally particle ID and trackID are not parts of hit information as they can not be known during data collection period (i.e., during real data taking).  Therefore, the list of hit data members should be from each experiment depending on what data can be collected from their detectors and used for digitization.  Therefore, there is no single definition of 'calorimeter hit' as all experiments may have different variation of their calorimeters and data definitions (of which their detectors can actually collect).

So regarding to Vladimir Ivantchenko's comments, we need know CMS calorimeter hit information (from CMSSW) or ATLAS hit information (from Athena) if we want to construct calorimeter hits for their (simulation) digitization processes.  Similar for their tracker hit definitions and so on. As I mentioned more than a couple of times (but might not explain clearly enough?), we, as a toolkit developer, need to provide only necessary virtual interfaces (in the Geant4 case, they are G4VHit, G4THitsCollection, G4VSensitiveDetector) and something like G4VUserDetectorConstruction::ConstructSDandField - then, user applications (something like our demo-loop) will add specific hit classes depending on specific user detectors or their data collection structure.  Sorry for repeating a long story for the SD discussion that you may already know, but I want to make sure that we clear separate what components should be inside the celeritas source and what others should go under the application area (i.e., user responsibility).  Anyway, we may start with a something simple like CalorimeterHit in the acceleritas example for any foreseeable our test cases which can be easily expandable later.

**Comment by sethrj** [comment]
Ahh, I had forgotten and was thinking of `G4Step` and `G4StepChange`. Thank you for the detailed explanation.

I know you've mentioned the virtual interfaces before, but the truth is that for users to write a "virtual interface" it will require them to write a kernel, manage data transfers, etc. I was hoping that to first order we might be able to have a couple of "out of the box" options for collecting data that could even hook up to their existing hit interfaces. That way even though their initial implementation might be far from optimal performance-wise, it would at least open a door to getting started.

With Acceleritas, would it be possible for us to reconstruct Geant4 step data to pass to existing sensitive detector routines in user code? If we know what data the user requires, and a few filtering criteria, we could perhaps reconstruct step information for those data and fill the unneeded bits with dummy values. At the meeting today maybe we could talk about what data is needed for some of  [VI's EM benchmark problems](http://vnivanch.web.cern.ch/vnivanch/tests.shtml).

**Comment by sethrj** [comment]
Prerequisite: #539 

The initial implementation of this will be an "easy but inefficient" way to hook into other frameworks. To first order we'll create a StepInterface subclass:
- Input is a vector of `G4VSensitiveDetector*` (or list of logical volumes or list of names?) plus a `StepSelection` object with the list of components needed
- We construct a map of logical volume name (`Label::from_geant`) to sensitive detector, probably an array to be easy (VecGeom logical volume ID maps to Celeritas `VolumeId`)
- For now let's be dumb and copy everything over to host

Future optimizations:
- device->host copy doesn't reallocate?
- do volume filtering on host
