### ISSUE TITLE
Implement value/xs interpolation ("physics tables") on GPU

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#3]
The physics tables contain energy-dependent, initialization-time physics data in Geant used during the event loop. It includes properties such as mean free paths (inverse of macroscopic cross section, used for sampling distance-to-interaction for "discrete" processes), energy deposition rates (dE/dx, for "continuous" processes), etc.

The dimensions on the data are ragged:
- Physics model (e.g., Bremsstrahlung, Klein–Nishina)
- Quantity (mean free path $`\lambda`$, microscopic cross section $`\sigma`$, energy loss $`dE/dx`$)
- Particle type (? for dE/dx)
- Material 
- Energy grid point

If a spline interpolation option is given (on a per-model basis), geant4 calculates and caches derivatives (but geantv calculates them on-the-fly) from the adjacent points.

The stored data in geant have different acceleration methods to speed lookup:
- Some "physics vectors" have a uniform logarithmic grid, even though interpolation is still linear-linear
- A couple of the EM process classes have grids that are split into "X" and "XPrim" where the split energy is typically 1 MeV (but perhaps subject to user optionss). For the case of mean free paths for compton
- (others... ???)

I'd like to implement the "physics vector" with the more generic ["value grid"](https://github.com/celeritas-project/celeritas/wiki/Code-design#classes-4) since none of the methods are specific to physics; it's just about grid lookup and value interpolation.

This should be similar to some of the stuff we've done in shift (physica/sce_cuda/xs_calculator) as well as geant4/geantv.

**Comment by sethrj** [comment]
@whokion I think a reasonable target for one of the core GPU kernels in celeritas is one that simply performs cross section and energy loss lookups, once per step (or less). Do you agree? If so, can you help determine requirements:
- What processes/models/groups of code need to perform energy-dependent lookups during stepping
- What access patterns can the lookups be grouped into? (e.g. process -> material; or process -> nuclide; or ...)
- What structure do the energy grids have? Are a substantial fraction of them uniform-in-log-energy, arbitrary-in-energy? This will determine the algorithm for looking up the grid points: whether we want acceleration special cases, always do log-space lookup, etc.
- How are the values interpolated on the energy grid? Are they always linear-linear in practice? Does the spline option ever get used?
- For all these questions, what abilities are needed for EM physics vs hadronic physics or other special caes ?

You might be able to work with @stognini and his geant exporter to determine bounds on the practical answers to these questions. By practical, I mean "what does Geant4 for HEP detector simulations actually do?" vs "what does Geant4 support?"

**Comment by whokion** [comment]
Brief answers for above questions.  May add more detailed descriptions later if necessary:
- What processes/models/groups of code need to perform energy-dependent lookups during stepping?
   A: All (standard Geant4) EM physics processes except positron annihilation need {energy, material}-dependent cross section table lookups to select the physics process and the proposed step length for a given step.  
- What access patterns can the lookups be grouped into? (e.g. process -> material; or process -> nuclide; or ...)
   A: In the process level, **{pid, material, energy}** is the typical triplet for the interaction cross section (i.e., lambda and dedx tables).  The further atomic dependence is only in the model level for evaluating its **differential** cross section (i.e., in the sampling analysis). 
- What structure do the energy grids have? Are a substantial fraction of them uniform-in-log-energy, arbitrary-in-energy? 
This will determine the algorithm for looking up the grid points: whether we want acceleration special cases, always do log-space lookup, etc.
  A: all (Geant4 standard) EM physics tables use the linear log-energy bin (the table type ==2, G4PhysicsLogVector) except the inverse range table which uses the type 4 (G4PhysicsFreeVector). 
- How are the values interpolated on the energy grid? Are they always linear-linear in practice? Does the spline option ever get used?
  A: always the linear interpolation unless the spline option is ON.
- For all these questions, what abilities are needed for EM physics vs hadronic physics or other special caes ?
  A: Geant4 hadronic physics processes do not typically use the G4PhysicsVector for their physics tables, but G4CrossSectionDataStore and etc.

**Comment by sethrj** [comment]
Excellent, thanks for the detailed responses @whokion. I didn't realize the hadronic processes used a totally different class for their lookups: that sounds like another can of worms.

**Comment by sethrj** [comment]
Basic value grids were implemented in https://github.com/celeritas-project/celeritas/pull/128 .

**Comment by sethrj** [comment]
Completed in #142 .
