### ISSUE TITLE
Fix discrete model selection and model applicability

### ISSUE THREAD

**Issue by amandalund** [celeritas-project/celeritas#356]
When sampling a discrete interaction, we sample a process using the per-process cross section calculated at the pre-step energy and then use the post-step energy to select the applicable model. Because of inconsistencies between the energy grid endpoints of the cross section tables and the model limits, it was possible for a process to be sampled but not have a model that applied at that energy. To get around this and make sure a model is always selected for the sampled process (but is this actually necessary, or can we just return an invalid model ID if none are applicable?), all our models currently have their lower applicable energy set to zero. This is wrong, but should produce correct results as long as the integral approach is used. However, without rejecting interactions based on the cross section at the post-step energy, we can end up e.g. with a stopped positron selecting bremsstrahlung because of the incorrect model energy bounds. We should figure out how to handle these inconsistencies and correctly set the model energy limits.

**Comment by sethrj** [comment]
Is this because of the cross section grid or because the change in energy over a step means the selected model has an energy threshold greater than the post-step energy of the particle? For the brems example, I think the lower energy bound for the model is because all the emitted secondaries are below the cutoff, i.e. putting 100% of the energy loss into the continuous term and eliminating the discrete term. In that case the correct approach should be to skip the discrete interaction (set `model={}`), right? Or do we need to recalculate all the process/model cross sections?

**Comment by amandalund** [comment]
> the change in energy over a step means the selected model has an energy threshold greater than the post-step energy of the particle

Yes, you are correct, that's what's happening in the brems example -- I agree in that case we should return an invalid model ID. Should we also skip the discrete interaction when the cross section tables extend below the model's lower energy limit, and the sampled process has no applicable model?

**Comment by amandalund** [comment]
For reference, these are energy limits we originally had for each model:
| Model | Energy bounds [MeV] |
| ------ | ----------- |
| Bethe-Heitler | [1.5, 1e5] |
| Klein-Nishina | [0.01, inf] |
| Livermore Rayleigh | [1e-5, 1e8] |
| Moller-Bhabha | [2e-3, 1e8] e-, [1e-3, 1e8] e+ |
| Seltzer-Berger | [1, 1e5] |
| EPlusGG | [0, 1e8] |
| Livermore photoelectric | [0, inf] |

I'm not sure these are all correct (e.g., shouldn't Bethe-Heitler extend down to 1.022 MeV, and up higher? Should Seltzer-Berger extend below 1 MeV?) It's never been totally clear to me where we get these values from.

**Comment by sethrj** [comment]
Yeah SB should have a lower bound equal to the minimum value on the tabular data, which I think is 1 MeV. The Bethe-Heitler should definitely be zero below twice the electron rest mass... but at least there's an assertion in place to check that it's not instantiated below that energy. Maybe it's zeros down there?

@stognini you probably know more than the rest of us why these energy grid points are chosen: are they simply a factor of secondary production cutoff (leading to minimum values for the incident particle energies) and the "points per decade" configuration option for cross section calculation?

At some point I suspect we'll have to bite the bullet and implement *all* the model differential cross section calculations,  so we can guarantee consistent values. We might even end up with our own "cross section processing" code so we don't have to do electron excitation on-the-fly (instead tabulating it). 🤔

**Comment by stognini** [comment]
> are they simply a factor of secondary production cutoff (leading to minimum values for the incident particle energies) and the "points per decade"

As far as I know, yes: production cuts and table binning.

Now, when it comes to the low energy limit, there are a bunch of odd points in G4 that, same as @amandalund, always confused me and we need to understand better. Take for example Klein-Nishina:
- Our limits: `[0.01, inf]`
- Geant4 activation limits, according to `G4VEmModel::[Low / High]EnergyActivationLimit()`: `Emin = 0 eV, Emax = 100 TeV`
- `G4KleinNishinaModel` has a `lowestSecondaryEnergy = 10*eV;`, where below that value, the model stops and kills the incident gamma (and assigns `E_kinetic = 0` to the scattered electron) -- so we activate the model at 0, but still don't do anything below a hardcoded `10 eV`.
- In the [Physics Reference Manual](https://geant4-userdoc.web.cern.ch/UsersGuides/PhysicsReferenceManual/html/electromagnetic/gamma_incident/compton/compton.html), we see: 
  >  When simulating the Compton scattering (...) an empirical cross section formula is used, which reproduces the cross section data down to 10 keV
  
  With uncertainties at the 10-20% level around 10 keV already.  

So we have an activation energy at `0`, a hardcoded limit at `10 eV`, a XS formula that reproduces XS data down to `10 keV`, and we have user-defined secondary thresholds.

So I think there are few points that are important to discuss, so we decide how we want to move forward:
- Do we want to replicate G4? Assign those numbers, call it a day. (Not my favorite...)
- Do we stick to where the real data ends (so for KN, no less than 10 keV)
- Do we extrapolate like G4, but let that as an option for the user? (Use at your own risk)

**Comment by sethrj** [comment]
Actually I think this is because I've set up the XS calculator to *extrapolate* cross sections outside the table range, rather than set to zero...

**Comment by amandalund** [comment]
Alright, so I think it _is_ ok to set the model lower energy limits to zero.  For gamma processes the energy won't change over the step, so as long as the process xs isn't nonzero below the model lower limit, we won't ever sample a process and not have an applicable model. For charged particle processes where the particle can lose energy over the step, the interactor might still be called for tracks with energy outside the applicable range of the model, but we have checks in place to return an `Interaction::from_unchanged()` if that happens.

We could alternatively set the model limits based on the process xs table energy grid (meaning the model applicabilities would be material dependent for energy loss processes), with the caveat that we need to be careful about the extrapolation behavior. We (and Geant4) extrapolate the cross section outside the energy grid. In Geant4 there's a "start from null" flag that's used in the construction of the lambda tables, which sets the first cross section value to zero for some processes: cross section for processes with this flag on (Compton, conversion, bremsstrahlung, ionization) will therefore be zero below the grid, but for those with it off (Rayleigh) it will be nonzero, so model limits should account for that.
