### ISSUE TITLE
Add GDML files into existing tests

### ISSUE THREAD

**Issue by mrguilima** [celeritas-project/celeritas#43]
More GDML files should be added to some of the existing tests, where it makes sense to widen test coverage.
Part of this issue is to create a few more GDML files, including more exotic shapes and features, e.g. 

- translations + rotations
- boolean operations on shapes
- less used / exotic shapes like torus, cut tubes, elliptical shapes, scaled shapes, and so forth

**Comment by sethrj** [comment]
I think we want to be careful about relying on Celeritas to do extensive testing of VecGeom. For unit testing, we should probably stick to a very simple representative case (have multiple materials and volumes, some adjacent volumes sharing the same material, some volumes nested). It is a good idea though to have acceptance tests with a whole zoo of shapes -- something where we can hammer the geometry and make sure that none of the edge cases are misbehaving.
