### ISSUE TITLE
Reorganize libraries and build tree

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#491]
## Library changes

The goal is to start incorporating into Celeritas the reusable components needed for Geant4 offloading.

- New `src/acceleritas` directory: move all `ext/geant` code there (GeantSetup, GeantImporter)
- Separate libraries for corecel, orange, celeritas, acceleritas
- Separate module for ROOT I/O wrappers: *just* the module? or also include the RootImporter/Exporter and have apps that use ROOT link against it?

```mermaid
graph LR;

acceleritas --> celeritas
acceleritas --> corecel
acceleritas --> Geant4
celeritas_root --> celeritas
celeritas_root --> ROOT
celeritas --> orange
celeritas --> corecel
orange --> corecel
```

## Build tree changes

Goal is to make the build tree look structurally like the installation.

- Set `CMAKE_LIBRARY_OUTPUT_DIRECTORY` at `src/` scope to put libraries in `build/${CMAKE_INSTALL_LIBDIR}` (i.e. `lib` or `lib64`): note that `root_generate_dictionary` only respects the default cmake variable, not the target property
- Set `CMAKE_RUNTIME_OUTPUT_DIRECTORY` in `app/` to put binaries in `build/bin`
- Similar for config files
- Similar include for generated config file paths

@pcanal If we put the generated ROOT files into `build/lib` but don't link against them, what's the best/most elegant way to get the dynamic library lookup for ROOT to find the correct `celeritas_root.so` module automatically?

**Comment by sethrj** [comment]
@pcanal I'm thinking first at build time: if the build files are in `build/lib`, would our tests at `test/blah` be able to find it? I guess not. So maybe it is best to keep the ROOT loading routines in the same library file, so that way tests and apps can be guaranteed to find it using the built-in `LC_LOAD_DYLIB` machO commands on macOS or `rpath` on Linux.

**Comment by pcanal** [comment]
Actually, it will also search the `rpath` (and probably the `LC_LOAD_DYLIB` but I can't test that).

> So maybe it is best to keep the ROOT loading routines in the same library file,

Either way, I don't really see any advantage to separate them, is there?

**Comment by sethrj** [comment]
> Either way, I don't really see any advantage to separate them, is there?

Only if it makes sense to treat the ROOT generated code as a "module" and the celeritas ROOT code as a "library"... but if the celeritas `Root{Ex,Im}porter` needs the generated module code then I guess we should keep them together.

**Comment by pcanal** [comment]
The ROOT does I/O then it will need the generated code (and it can get it either via explicit linking of via autoloading of the library)
