### ISSUE TITLE
Integrate "Acceleritas" components into celeritas

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#561]
I'd like a new "acceleritas" library inside celeritas to start codifying some of the reusable components for integrating Celeritas into generic Geant4-based applications/workflows for EM offloading. It should be built if Geant4 and VecGeom are enabled.

Setup capabilities:
- Until #557 is implemented and reliable, export a GDML with the detector world volume and import it into vecgeom
- Use the `GeantImporter` class to load EM data into celeritas (requires physics data to be built)
- Take a list of sensitive detectors (names? SD pointers? logical volume pointers?) that need to interact with offloaded EM particles
- Construct all these as "params" data shared between threads
- Create persistent `SimpleTransporter` instances on each thread so that they can have independent states (will probably need stream IDs, see #418)
- Maybe a fixed set of "along step" kernel implementations? Should we add the parameterized CMS field to the main codebase first?

I'm not sure when these things can/should be constructed because of the interdependencies:
- params construction requires geometry and physics
- geometry will require detector construction to be complete
- physics requires `G4RunManager::RunInitialization` to populate physics tables
- user action (sensitive detectors) requires geometry and SD volume names

I'm visualizing that most or all of the classes in the top-level `src/acceleritas` dir will inherit from Geant4 objects, so those classes should use Geant4 naming conventions (and maybe even conventions like using accessors to mutate the classes after construction? though I'd like to avoid that).

We'll need a new `StepInterface` subclass for creating `G4Step` that gets sent to sensitive detectors. (Question: how are SD classes multithreaded?)

We'll probably want a new thread-local class instance to manage the thread-local offload execution, and share it across multiple Geant4 callback classes:
- Set event ID (`G4UserEventAction`)
- Add tracks to offload (`G4UserTrackingAction`)
- Launch tracks when enough have been queued, which will implicitly call back to the sensitive detector classes
- Run any unqueued tracks at the end of event

**Comment by sethrj** [comment]
![g4step](https://user-images.githubusercontent.com/741229/204282217-f9c3be80-6d7c-45eb-af90-23346cfa85c1.png)

**Comment by whokion** [comment]
Overall it looks a good path/plan for the integration.  Regarding to SD hits for MT, Geant4MT will take care of merging hits collections (root files created by each thread) at the end of Run.  For the tasking approach, we may need  to create a user I/O (conversion or merging) task at the end of Run.  Concerning to the plot, why does Celeritas produce "Processed hits" in addition to the pipeline through "Partial G4Step? Is there any exclusive hits categories produced solely by Celeritas?

**Comment by sethrj** [comment]
The "processed hits" was meant as an alternative to the "partial g4step" for more performant (but more app-specific) integration.

@whokion can you help elucidate the ordering of when the geant physics tables are populated, when the geometry is constructed, and when the different "actions" are called (and for which threads)? We need to figure out the best place to construct the shared celeritas data and from there how to construct the thread-local states.

Maybe @stognini @amandalund and I should have a mini hackathon this week to try to get something working?

**Comment by sethrj** [comment]
Hackathon successful: see #567, #575, #576, #577, #578, #579, #580, #581, #582, #583
