### ISSUE TITLE
README.md is out of date

### ISSUE THREAD

**Issue by paulromano** [celeritas-project/celeritas#570]
Some of the file references are out of date, specifically:
https://github.com/celeritas-project/celeritas/blob/2e022e38ed67c5181319d23ee301a505b37703ae/README.md?plain=1#L21

https://github.com/celeritas-project/celeritas/blob/2e022e38ed67c5181319d23ee301a505b37703ae/README.md?plain=1#L34

**Comment by sethrj** [comment]
That PR is almost done but let me just move that commit to a new PR.
