### ISSUE TITLE
Debug assertion failure: EnergyLossApplier.hh:77: `step_limit->action != track.boundary_action()`

### ISSUE THREAD

**Issue by amandalund** [celeritas-project/celeritas#620]
#### Failure:
```json
    "failure": {
     "condition": "step_limit->action != track.boundary_action()",
     "file": "/home/alund/celeritas_project/celeritas/src/celeritas/global/alongstep/detail/EnergyLossApplier.hh",
     "line": 77,
     "type": "DebugError",
     "which": "internal assertion failed"
    }  
```
#### Regression problem:
simple-cms+field+msc-vecgeom-cpu

#### Diagnosis:
Similar to #615: the electron step is limited by the distance to boundary = 5.25225251573336250e-07. Since it's a geo-limited step, `UrbanMscScatter` recalculates the true path length as the range = 5.19256630037738303e-06. Because the step length is equal to the range, the particle loses all energy over the step, but the action is still boundary crossing.

**Comment by sethrj** [comment]
@amandalund was this also for a 10 MeV electron? I bet your fix #642 also fixed this.
