### ISSUE TITLE
Improve CI infrastructure

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#698]
- ~~[Dockerhub is getting rid of the free teams tier](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/) but maybe our images will stay live?~~ Apparently docker is [no longer ending it](https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/)
- Kokkos builds block the single HIP executor and each one of those seems to take 2–6 hours (@dalg24 ) whereas our pipelines take <10 minutes
- Jenkins/blueocean annoys the shit out of me with the number of clicks it takes to get to a broken test and how it autorefreshes in the background
- Our github pages website requires manual updating

Ideally we could:
- [x] Auto-publish documentation (moved from https://github.com/celeritas-project/celeritas/issues/592)
- [ ] View results on CDash instead of jenkins/blue ocean
- [x] Use github actions for better github integration (#1020)
- [x] Not have to maintain our own machines for HIP and CUDA, nor to share a single machine with Kokkos

Resources:
- [Dockerfile support for GitHub Actions](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions)
- [Creating a Docker container action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)
- [Apply for docker open source tier](https://www.docker.com/community/open-source/application/)
- [Building CI with CDash](https://embeddeduse.com/2022/05/02/building-a-ci-pipeline-with-ctest-and-cdash/)

TODO for Github CI:
- [ ] Fix the issues with examples
  * [ ] asan build needs `-fsanitize=address` in downstream example
  * [ ] rocm+ndebug (static libs) fails to propagate the HIP library linkage
  * [x] SimpleOffload::Build crashes because ~~MTLogger is called before run manager completes initialization~~ default run manager is "task" which returns zero threads on the first call
  * [ ] VecGeom build on Ubuntu requires `-Wl,--no-as-needed` which we provide to Celeritas via `CMAKE_{SHARED|EXE}_LINKER_FLAGS`: maybe @pcanal 's RDC code needs to propagate these? Should this be vecgeom's responsibility?
- [x] Use a shallow clone and `git describe` or some better way of fetching tags
- [ ] Improve docker images
  * Add ccache to the build image and use it
  * Avoid custom user ID; GitHub requires root
  * Install all supported geant4 versions for a small build matrix
  * Fix entry point so that we don't have to manually source `/etc/profile` and re-export variables
- [x] Add separate build matrix for geant4 versions (to test minimum and maximum supported)
- [x] Add ~~nightly~~ minimal build matrix for various compilers on raw hardware (earliest GCC through latest, multiple clang versions)
- [x] Add automatic clang formatting and/or fix?
- [x] Add documentation
- [x] Only do a simple build for "draft" PRs

**Comment by dalg24** [comment]
We are having issues with our AMD testing machines.  We used to have 4 executors and we are down to 2 at the moment.

**Comment by sethrj** [comment]
TODO:
- [ ] Use cmake action to tag errors/warnings in source code: [run-cmake](https://github.com/lukka/run-cmake)?
- [ ] Lint with clang-tidy? https://github.com/ZedThree/clang-tidy-review
- [ ] Clang format action: [cpp linter action](https://cpp-linter.github.io/cpp-linter-action/) or just add git-clang-format [manually](https://github.com/boutproject/BOUT-dev/blob/master/.github/workflows/clang-format.yml)
- [x] Windows runner: [github hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners)
