### ISSUE TITLE
Extend GeantGeoConverter for G4ReflectedSolid

### ISSUE THREAD

**Issue by whokion** [celeritas-project/celeritas#750]
While running demo-geant-integration with [cms-run3.gdml](https://github.com/celeritas-project/benchmarks/blob/main/full-cms-test/input/cms-run3.gdml), there are in-memory GeantGeoConverter failures for G4ReflectedSolid,

> internal assertion failed: SoftEqual{0.01}(v1,v2)

from [GeantGeoConverter.cc](https://github.com/celeritas-project/celeritas/blob/develop/src/celeritas/ext/detail/GeantGeoConverter.cc#LL305C28-L305C28).

By-passing the assert, hit the next assertion in the downstream at

> src/celeritas/mat/MaterialTrackView.hh:102:
> celeritas: internal assertion failed: other.material_id < params_.materials.size()

See the log file,  [run3-cms-test.log](https://github.com/celeritas-project/celeritas/files/11431267/run3-cms-test.log) using VecGeom v1.2.2 (same behavior with CMSSW+celeritas+VecGeom v1.2.1)

**Comment by sethrj** [comment]
Thanks @whokion . The failure is because:
```
/work1/celeritas/syjun/celeritas/src/celeritas/src/celeritas/geo/GeoMaterialParams.cc:157: warning: Some geometry volumes do not have known material IDs: world_volume@0x7f7110475c60, cms_OCMS@0x7f7110475bc0, cms_CMSE@0x7f7110475b20, cmsextent_CMStoZDC@0x7f7110474c20, cmsextent_ZDCtoFP4201@0x7f7110474cc0 ....
```
so next I can try to figure out why the volume names aren't being found correctly.

**Comment by sethrj** [comment]
OK also just a note to self: the `G4ReflectedSolid` is created via `G4ReflectionFactory` in `G4GDMLReadStructure::PhysvolRead` by inspecting the transformation matrix to see if it has a negative scale factor (e.g., `z=-1` scaling).
