### ISSUE TITLE
Fix geometry track initialization on device

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#77]
In #38 we tested and added support for initializing tracks on device using the GlobalLocator, as of [this VecGeom PR](https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/760). Unfortunately our testing wasn't thorough enough, and even though initialization seems to work in the very simple tests we added, initialization fails catastrophically for the CMS models, and it also fails when trying to initialize the two-box test case outside of the world volume.

See also https://github.com/apt-sim/AdePT/issues/39 .

**Comment by sethrj** [comment]
@mrguilima You've been working on this with https://github.com/celeritas-project/celeritas/pull/90 adding additional initialization checks that previously failed, yes? Can you post any updates on the CMS trace here as you get them?

I think it would also be good for posterity to cross-link this issue with any future fixes to initialization in VecGeom, but here are the two that I think were prerequisite for your four-boxes initialization to work:
- https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/760
- https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/768

**Comment by mrguilima** [comment]
Here are two more VecGeom fixes affecting GDML parsing, which were affecting the track initialization:

- https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/776
- https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/777

**Comment by sethrj** [comment]
I think with #90 we can call this issue closed. Thanks @mrguilima for digging into this and adding a more robust geometry test.
