### ISSUE TITLE
Add "fast simulation" interface to accel

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#823]
If we want to support exact leptonuclear physics or Bertini cascades (#431 ) we'll need to return particles to Geant4, which will require us to expose Celeritas to Geant4 using the `G4VFastSimulationModel` interface, which needs the `flush` method introduced in Geant4@11.0 (see `param-V11-00-01`).

We also probably want to support offloading EM particles only for the inside of the detector, so we don't have to return hits to the muon calorimeter or any of the far detectors.

**Comment by drbenmorgan** [comment]
@sethrj, this would also be useful as part of the ATLAS integration efforts so I could help with this if needed.

NB: ATLAS of course are currently using 10.6, but at least at this stage testing of Celeritas can also use 11.0. ATLAS could also look at back porting `flush()` et al to their production patches to 10.6.

**Comment by sethrj** [comment]
That would be fantastic @drbenmorgan ! I don't think it's a very heavy lift and we'd appreciate the help.

**Comment by drbenmorgan** [comment]
O.k., I want to get the first pass ATLAS integration in FullSimLight underway before this, but feel free to assign to me (and then chase as needed!).
